# Generated by Django 5.2.5 on 2025-10-20 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['-fecha_consulta'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='consulta',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendacita'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='examenes_solicitados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='notas_privadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prescripciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='proxima_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='saturacion_oxigeno',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='core_pacien_estado_176713_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tipo_sangre'], name='core_pacien_tipo_sa_87b6fe_idx'),
        ),
    ]
