# Generated by Django 5.2.5 on 2025-11-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='core_pacien_estado_176713_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tipo_sangre'], name='core_pacien_tipo_sa_87b6fe_idx'),
        ),
    ]
