# Generated by Django 5.2.5 on 2025-11-03 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSuscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='administrador',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='agendacita',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='componenteui',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='horariomedico',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='medico',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='medicoespecialidad',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='permisocomponente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='registrobackup',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='rol',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='tipocomponente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientesuscriptor'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='core_pacien_estado_176713_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tipo_sangre'], name='core_pacien_tipo_sa_87b6fe_idx'),
        ),
    ]
