# Generated by Django 5.2.5 on 2025-11-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('urgencia_default', models.CharField(choices=[('Rutina', 'Rutina'), ('Urgente', 'Urgente'), ('Emergencia', 'Emergencia')], default='Rutina', max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('urgencia', models.CharField(choices=[('Rutina', 'Rutina'), ('Urgente', 'Urgente'), ('Emergencia', 'Emergencia')], max_length=15)),
                ('indicaciones_especificas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=15)),
                ('resultados', models.TextField(blank=True, null=True)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_examen', to='core.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoexamen')),
            ],
            options={
                'verbose_name': 'Solicitud de Examen',
                'verbose_name_plural': 'Solicitudes de Exámenes',
            },
        ),
    ]
