# Generated by Django 5.2.5 on 2025-11-25 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='fecha_receta',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
