# Generated by Django 5.2.5 on 2025-11-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_receta_fecha_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallereceta',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.receta'),
        ),
    ]
