"""
Django settings for gestion_documental_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@_zy*lwa!651h7gs-z7jwch_@n3#6iy+$4ijcmu=(_y3puso0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost:4200', 'abc-gestion-documental-backend.duckdns.org', 'localhost', '127.0.0.1', '0.0.0.0', '192.168.0.6', '192.168.0.4']
CORS_ALLOWED_ORIGINS = [
    "https://gestion-documental-frontend.vercel.app",
    "http://localhost:4200",
    "http://localhost:8000",
    "http://192.168.0.6:4200",  # Si Angular se accede desde red local
    "http://127.0.0.1:8100",    # Ionic o Flutter en navegador
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework',
    'core',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'dbbackup',
    'django_celery_beat',
    'django_celery_results',
]

# Configuración de backup
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': 'backups/'}

# Para PostgreSQL
DBBACKUP_CONNECTOR_MAPPING = {
    'django.db.backends.postgresql': 'dbbackup.db.postgresql.PgDumpConnector',
}

# Directorio de backups con permisos adecuados
# BACKUP_DIR = '/var/backups/app_backups'
BACKUP_DIR = os.path.join(BASE_DIR, 'backups')

# Asegurar que el directorio existe y tiene permisos
if not os.path.exists(BACKUP_DIR):
    os.makedirs(BACKUP_DIR, mode=0o755)

# En views.py, modificar el directorio para producción
backup_dir = os.environ.get('BACKUP_DIR', 'backups')

# Configuración Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/La_Paz'

# Para producción en GCP, usar Redis Cloud o Memorystore
if os.environ.get('ENVIRONMENT') == 'production':
    CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
    CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestion_documental_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_documental_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gdocumental_db',
        'USER': 'postgres',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

AUTH_USER_MODEL = 'core.Usuario'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGES = [
    ('es', 'Spanish'),
]
LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#opcional
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',],
}

SIMPLE_JWT = {
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),        # El token de acceso durará 7 días
    'REFRESH_TOKEN_LIFETIME': timedelta(days=10),      # El token de refresco durará 10 días
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),                  # Usa "Bearer <token>" en los headers
}

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Si usas cookies/sessions
CSRF_TRUSTED_ORIGINS = [
    "https://gestion-documental-frontend.vercel.app",
    "https://abc-gestion-documental-backend.duckdns.org",
]

# Middleware adicional para headers
class CorsMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        response = self.get_response(request)
        response['Access-Control-Allow-Origin'] = 'https://gestion-documental-frontend.vercel.app'
        response['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS, PUT, DELETE'
        response['Access-Control-Allow-Headers'] = 'Authorization, Content-Type, X-CSRFToken'
        response['Access-Control-Allow-Credentials'] = 'true'
        return response


# Agrega el middleware al final
MIDDLEWARE.append('gestion_documental_backend.settings.CorsMiddleware')

# Configuración Celery Beat para backups automáticos
CELERY_BEAT_SCHEDULE = {
    # Para testing - cada 3 minutos
    #'backup-test-cada-3min': {
    #    'task': 'core.tasks.realizar_backup_automatico',
    #    'schedule': crontab(minute='*/3'),  # Cada 3 minutos
    #},
    
    # Para producción - una vez al día
    'backup-diario-2am': {
        'task': 'core.tasks.realizar_backup_automatico',
        'schedule': crontab(hour=2, minute=0),  # 2:00 AM diario
    },
    'limpieza-semanal': {
        'task': 'core.tasks.realizar_limpieza_backups',
        'schedule': 604800.0,  # 7 días en segundos
        # O usar crontab:
        # 'schedule': crontab(hour=3, minute=0, day_of_week=0),  # Domingos a las 3:00 AM
    },
}

# En settings.py - Agregar estas configuraciones
#DBBACKUP_POSTGRESQL_BACKUP_CMD = r'C:\Program Files\PostgreSQL\16\bin\pg_dump.exe'
#DBBACKUP_POSTGRESQL_RESTORE_CMD = r'C:\Program Files\PostgreSQL\16\bin\psql.exe'

# O si no funciona, prueba con:
DBBACKUP_POSTGRESQL_DUMP_CMD = r'C:\Program Files\PostgreSQL\16\bin\pg_dump.exe'
DBBACKUP_POSTGRESQL_RESTORE_CMD = r'C:\Program Files\PostgreSQL\16\bin\psql.exe'

# También agrega estas configuraciones adicionales
DBBACKUP_POSTGRESQL_IGNORE_TABLES = []
DBBACKUP_POSTGRESQL_EXTENSION = 'psql'